import random
import time
import tracemalloc

from pygame.math import Vector2

from config import CELL_NUMBER
from enums import SimMode
from test_algorithms.a_star import informed_a_star
from test_algorithms.greedy_bfs import informed_greedy_bfs
# from search.bfs import BFSPathfinder
# from search.dijkstra import DijkstraPathfinder
from test_algorithms.search_bridge import bfs_bridge, dijkstra_bridge

# This module was created to handle controlling the snake movement
# in line with the selected algorithm.
# It should alleviate the need to make too many changes to main/engine

# References the enums to hopefully help with easier GUI integration.
ALGORITHM_SELECTION = {
    SimMode.BFS: bfs_bridge,
    SimMode.GBFS: informed_greedy_bfs,
    SimMode.DIJK: dijkstra_bridge,
    SimMode.ASTAR: informed_a_star,
}


def get_next_direction(mode, engine) -> Vector2:
    """
    The get_next_direction function essentially takes the simulated input from the
    selected algorithm and allows the sake to be moved in accordance to the path
    generated by the algorithm.
    """
    head = engine.snake.body[0]

    algorithm = ALGORITHM_SELECTION.get(mode)
    path = algorithm(
        (int(head.x), int(head.y)),
        (int(engine.fruit.pos.x), int(engine.fruit.pos.y)),
        [(int(b.x), int(b.y)) for b in engine.snake.body],
        CELL_NUMBER
    )

    if path and len(path) > 1:
        nx, ny = path[1]
        return Vector2(nx - head.x, ny - head.y)

    # failsafe to safe movement instead of making blind movements
    return get_safe_move(engine)


# code from GPT
def get_safe_move(engine):
    head = engine.snake.body[0]
    current_dir = engine.snake.direction

    directions = [
        Vector2(1, 0),
        Vector2(-1, 0),
        Vector2(0, 1),
        Vector2(0, -1)
    ]

    safe_moves = []

    for d in directions:
        # prevent reversing
        if current_dir + d == Vector2(0, 0):
            continue

        next_pos = head + d

        # wall check
        if not (0 <= next_pos.x < CELL_NUMBER and 0 <= next_pos.y < CELL_NUMBER):
            continue

        # self collision check
        if next_pos in engine.snake.body:
            continue

        safe_moves.append(d)

    if safe_moves:
        return random.choice(safe_moves)

    # failsafe to previous direction if possible
    if engine.snake.prev_direction != Vector2(0, 0):
        return engine.snake.prev_direction

    return Vector2(1, 0)  # last-resort default


def update_direction(engine, curr_mode: SimMode) -> tuple[int, float]:
    """
    The update_direction function is the link to the main module game loop
    where the function is called to pass the output of the get_next_direction function
    to the engine.

    Return the float representing the execution time for the algorithm
    """
    snake_head = engine.snake.body[0]
    peak_mem: int = peak_memory(ALGORITHM_SELECTION.get(curr_mode),
                                (int(snake_head.x), int(snake_head.y)),
                                (int(engine.fruit.pos.x),
                                 int(engine.fruit.pos.y)),
                                [(int(b.x), int(b.y)) for b in engine.snake.body],
                                CELL_NUMBER)

    # start timer for execution time
    start = time.perf_counter()

    prev_direction = engine.snake.direction
    new_dir = get_next_direction(curr_mode, engine)

    if new_dir is None or new_dir == Vector2(0, 0):
        new_dir = get_safe_move(engine)

    # checks to ensure a new direction can be set
    if new_dir is not None:
        engine.snake.direction = new_dir
        engine.snake.prev_direction = prev_direction

    end = time.perf_counter()

    # return execution time
    exec_time = end - start

    return peak_mem, exec_time


def peak_memory(algorithm, pos_h, pos_f, body, cell_number) -> int:
    """
    The peak_memory function uses python's tracemalloc standard module to measure
    the peak memory usage of any algorithm appropriate that is passed to it as an argument.
    The returned value is in bytes.

    To NOTE: From what I understand, or we have learned, informed and uninformed
    algorithms should use different amounts of memory space, so showing the 
    peak memory usage should also work as an identifier.
    Although probably not as informative as having the real-time memory usage,
    this should work fine as a good sub replacement.

    Alternatively, We could introduce tracemalloc snapshots at the point of the fruit being
    eaten, which should in theory provide some more appealing graphs.

    This will also require a small change to the engine.py for a listener.
    The snapshot function and the start and stop addons(?) as needed.

    Also, the suitable output method needs to be discussed for memory output.
    """
    tracemalloc.start()
    algorithm(pos_h, pos_f, body, cell_number)
    current, peak = tracemalloc.get_traced_memory()
    tracemalloc.stop()

    return peak
