from pygame.math import Vector2
from config import CELL_NUMBER
from enums import SimMode
from test_algorithms.a_star import informed_a_star
from test_algorithms.greedy_bfs import informed_greedy_bfs
# from search.bfs import BFSPathfinder
# from search.dijkstra import DijkstraPathfinder

# This module was created to handle controlling the sanke movement
# in line with the selected algorithm.
# It should alleviate the need to make too many change to main/engine

ALGORITHM_SELECTION = {
    # References the enums to hopefully help with easier GUI integration.

    # SimMode.BFS: ,
    SimMode.GBFS: informed_greedy_bfs,
    # SimMode.DIJK: ,
    SimMode.ASTAR: informed_a_star,
    # SimMode.HUMAN: None
}

def get_next_direction(mode, engine):
    """
    The get_next_direction function essentially take the simulated input from the 
    selected algorithm and allows the sake to be moved in accordance to the path 
    generated by the algorithm.
    """
    head = engine.snake.body[0]

    algorithm = ALGORITHM_SELECTION.get(mode)
    path = algorithm(
        (int(head.x), int(head.y)),
        (int(engine.fruit.pos.x), int(engine.fruit.pos.y)),
        [(int(b.x), int(b.y)) for b in engine.snake.body],
        CELL_NUMBER
    )

    if path and len(path) > 1:
        nx, ny = path[1]
        return Vector2(nx - head.x, ny - head.y)
    
    return engine.snake.direction

# For potentiallly easier enum integration
current_mode = SimMode.ASTAR

def update_direction(engine):
    """
    The update_direwction function is the link to the the main module game loop
    where the function is called to pass the output of the get_next_direction function
    to the engine.
    """
    engine.snake.direction = get_next_direction(current_mode, engine)
    engine.update()